ServiceConfig:
  env: local
  redis_addr: "127.0.0.1:6379"
  redis_username: ""
  redis_password: ""
LogConfig:
  log_level: DEBUG
  log_path: server.log
  log_mode: file
ApiKeys:
  openai_api: xxx
  serp_api: yyy
  active_loop_api: zzz
