version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    networks:
      - engine_net
    container_name: 'engine-elasticsearch'
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    networks:
      - engine_net
    container_name: "engine-kibana"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  engine_net:
    driver: bridge