apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: {fleetName}-autoscaler
  namespace: default
spec:
  fleetName: {fleetName}
  policy:
    buffer:
      bufferSize: 10
      maxReplicas: 40
      minReplicas: 10
    type: Buffer
